/* Generated by Pyrex 0.9.8.5 on Tue Feb 10 07:47:20 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static char __pyx_mdoc[] = "This module provides helper functions for the pointcloud module.\n";

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from _pointcloud */


/* Declarations from implementation of _pointcloud */

typedef void *__pyx_t_11_pointcloud_PtcPointCloud;

typedef int (*__pyx_t_11_pointcloud_PtcReadDataPointPtr)(__pyx_t_11_pointcloud_PtcPointCloud,float *,float *,float *,float *);

typedef int (*__pyx_t_11_pointcloud_PtcWriteDataPointPtr)(__pyx_t_11_pointcloud_PtcPointCloud,float *,float *,float,float *);


static char __pyx_k1[] = "Failed to read data point from point cloud file";
static char __pyx_k2[] = "Failed to write data point into point cloud file";


static PyObject *__pyx_k1p;
static PyObject *__pyx_k2p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k1p, 0, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_k2p, 0, __pyx_k2, sizeof(__pyx_k2)},
  {0, 0, 0, 0}
};



/* Implementation of _pointcloud */

static PyObject *__pyx_f_11_pointcloud_readDataPoints(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_11_pointcloud_readDataPoints[] = "Read a sequence of data points.\n    \n    readFuncLoc is the location of the PtcReadDataPoint function pointer.\n    ptcHandle is the open point cloud handle. numPoints is the number of\n    points that should be read.\n    All the *Buf variables are the respective buffers where the data is written\n    to. *Stride is the number of floats to advance the pointers to get to the\n    next data location. The buffers must be large enough to hold numPoints\n    items.\n    numPoints must at least be the number of points that are still left\n    in the file (otherwise the function may generate an exception or return\n    bogus values, whatever the underlying RenderMan implementation does).\n    ";
static PyObject *__pyx_f_11_pointcloud_readDataPoints(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_readFuncLoc;
  long __pyx_v_ptcHandle;
  long __pyx_v_numPoints;
  long __pyx_v_pointBuf;
  int __pyx_v_pointStride;
  long __pyx_v_normalBuf;
  int __pyx_v_normalStride;
  long __pyx_v_radiusBuf;
  int __pyx_v_radiusStride;
  long __pyx_v_dataBuf;
  int __pyx_v_dataStride;
  __pyx_t_11_pointcloud_PtcReadDataPointPtr __pyx_v_PtcReadDataPoint;
  __pyx_t_11_pointcloud_PtcPointCloud __pyx_v_pointCloud;
  float *__pyx_v_pntPtr;
  float *__pyx_v_normalPtr;
  float *__pyx_v_radiusPtr;
  float *__pyx_v_dataPtr;
  int __pyx_v_n;
  int __pyx_v_res;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"readFuncLoc","ptcHandle","numPoints","pointBuf","pointStride","normalBuf","normalStride","radiusBuf","radiusStride","dataBuf","dataStride",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "llllililili", __pyx_argnames, &__pyx_v_readFuncLoc, &__pyx_v_ptcHandle, &__pyx_v_numPoints, &__pyx_v_pointBuf, &__pyx_v_pointStride, &__pyx_v_normalBuf, &__pyx_v_normalStride, &__pyx_v_radiusBuf, &__pyx_v_radiusStride, &__pyx_v_dataBuf, &__pyx_v_dataStride)) return 0;

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":63 */
  __pyx_v_PtcReadDataPoint = (((__pyx_t_11_pointcloud_PtcReadDataPointPtr *)__pyx_v_readFuncLoc)[0]);

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":64 */
  __pyx_v_pointCloud = ((__pyx_t_11_pointcloud_PtcPointCloud)__pyx_v_ptcHandle);

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":73 */
  __pyx_v_pntPtr = ((float *)__pyx_v_pointBuf);

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":74 */
  __pyx_v_normalPtr = ((float *)__pyx_v_normalBuf);

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":75 */
  __pyx_v_radiusPtr = ((float *)__pyx_v_radiusBuf);

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":76 */
  __pyx_v_dataPtr = ((float *)__pyx_v_dataBuf);

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":79 */
  __pyx_v_n = 0;

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":80 */
  while (1) {
    __pyx_1 = (__pyx_v_n < __pyx_v_numPoints);
    if (!__pyx_1) break;

    /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":81 */
    __pyx_v_res = __pyx_v_PtcReadDataPoint(__pyx_v_pointCloud,__pyx_v_pntPtr,__pyx_v_normalPtr,__pyx_v_radiusPtr,__pyx_v_dataPtr);

    /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":82 */
    __pyx_1 = (__pyx_v_res == 0);
    if (__pyx_1) {
      __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
      Py_INCREF(__pyx_k1p);
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_k1p);
      __pyx_3 = PyObject_CallObject(PyExc_IOError, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __Pyx_Raise(__pyx_3, 0, 0);
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":84 */
    __pyx_v_pntPtr += __pyx_v_pointStride;

    /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":85 */
    __pyx_v_normalPtr += __pyx_v_normalStride;

    /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":86 */
    __pyx_v_radiusPtr += __pyx_v_radiusStride;

    /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":87 */
    __pyx_v_dataPtr += __pyx_v_dataStride;

    /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":88 */
    __pyx_v_n += 1;
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_pointcloud.readDataPoints");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_11_pointcloud_writeDataPoints(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_11_pointcloud_writeDataPoints[] = "Write a sequence of data points.\n    \n    writeFuncLoc is the location of the PtcWriteDataPoint function pointer.\n    ptcHandle is the open point cloud handle. numPoints is the number of\n    points that should be written.\n    All the *Buf variables are the respective buffers where the data is read\n    from. *Stride is the number of floats to advance the pointers to get to the\n    next data location. The buffers must contain at least numPoints values.\n    ";
static PyObject *__pyx_f_11_pointcloud_writeDataPoints(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_writeFuncLoc;
  long __pyx_v_ptcHandle;
  long __pyx_v_numPoints;
  long __pyx_v_pointBuf;
  int __pyx_v_pointStride;
  long __pyx_v_normalBuf;
  int __pyx_v_normalStride;
  long __pyx_v_radiusBuf;
  int __pyx_v_radiusStride;
  long __pyx_v_dataBuf;
  int __pyx_v_dataStride;
  __pyx_t_11_pointcloud_PtcWriteDataPointPtr __pyx_v_PtcWriteDataPoint;
  __pyx_t_11_pointcloud_PtcPointCloud __pyx_v_pointCloud;
  float *__pyx_v_pntPtr;
  float *__pyx_v_normalPtr;
  float *__pyx_v_radiusPtr;
  float *__pyx_v_dataPtr;
  int __pyx_v_n;
  int __pyx_v_res;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"writeFuncLoc","ptcHandle","numPoints","pointBuf","pointStride","normalBuf","normalStride","radiusBuf","radiusStride","dataBuf","dataStride",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "llllililili", __pyx_argnames, &__pyx_v_writeFuncLoc, &__pyx_v_ptcHandle, &__pyx_v_numPoints, &__pyx_v_pointBuf, &__pyx_v_pointStride, &__pyx_v_normalBuf, &__pyx_v_normalStride, &__pyx_v_radiusBuf, &__pyx_v_radiusStride, &__pyx_v_dataBuf, &__pyx_v_dataStride)) return 0;

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":106 */
  __pyx_v_PtcWriteDataPoint = (((__pyx_t_11_pointcloud_PtcWriteDataPointPtr *)__pyx_v_writeFuncLoc)[0]);

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":107 */
  __pyx_v_pointCloud = ((__pyx_t_11_pointcloud_PtcPointCloud)__pyx_v_ptcHandle);

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":116 */
  __pyx_v_pntPtr = ((float *)__pyx_v_pointBuf);

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":117 */
  __pyx_v_normalPtr = ((float *)__pyx_v_normalBuf);

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":118 */
  __pyx_v_radiusPtr = ((float *)__pyx_v_radiusBuf);

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":119 */
  __pyx_v_dataPtr = ((float *)__pyx_v_dataBuf);

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":122 */
  __pyx_v_n = 0;

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":123 */
  while (1) {
    __pyx_1 = (__pyx_v_n < __pyx_v_numPoints);
    if (!__pyx_1) break;

    /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":124 */
    __pyx_v_res = __pyx_v_PtcWriteDataPoint(__pyx_v_pointCloud,__pyx_v_pntPtr,__pyx_v_normalPtr,(__pyx_v_radiusPtr[0]),__pyx_v_dataPtr);

    /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":125 */
    __pyx_1 = (__pyx_v_res == 0);
    if (__pyx_1) {
      __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
      Py_INCREF(__pyx_k2p);
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_k2p);
      __pyx_3 = PyObject_CallObject(PyExc_IOError, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __Pyx_Raise(__pyx_3, 0, 0);
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":127 */
    __pyx_v_pntPtr += __pyx_v_pointStride;

    /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":128 */
    __pyx_v_normalPtr += __pyx_v_normalStride;

    /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":129 */
    __pyx_v_radiusPtr += __pyx_v_radiusStride;

    /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":130 */
    __pyx_v_dataPtr += __pyx_v_dataStride;

    /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":131 */
    __pyx_v_n += 1;
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_pointcloud.writeDataPoints");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"readDataPoints", (PyCFunction)__pyx_f_11_pointcloud_readDataPoints, METH_VARARGS|METH_KEYWORDS, __pyx_doc_11_pointcloud_readDataPoints},
  {"writeDataPoints", (PyCFunction)__pyx_f_11_pointcloud_writeDataPoints, METH_VARARGS|METH_KEYWORDS, __pyx_doc_11_pointcloud_writeDataPoints},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC init_pointcloud(void); /*proto*/
PyMODINIT_FUNC init_pointcloud(void) {
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("_pointcloud", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;};

  /* "/Users/baas/src/cgkit/pyrex/pyx/_pointcloud.pyx":90 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("_pointcloud");
}

static char *__pyx_filenames[] = {
  "_pointcloud.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
